GET http://localhost:4000/api/v1/employees HTTP/1.1

###
POST http://localhost:4000/api/v1/employees HTTP/1.1
Content-Type: application/json

{
    "name" : "Kim", 
    "lastname" : "Garces",
    "nit" : 1067943114,
    "type_contract" : "indefinido",
    "birth_date" : "18-08-1995" , 
    "address" : "Bogota DC",
    "phone" : 3013570670,
    "email" : "kim@gmail.com"
}

###
PUT http://localhost:4000/api/v1/employees/5fa871553762f41848cae61f HTTP/1.1
Content-Type: application/json

{
    "name" : "Kim", 
    "lastname" : "Garces",
    "nit" : 1067943114,
    "type_contract" : "definido",
    "birth_date" : "18-08-1995" , 
    "address" : "Bogota DC",
    "phone" : 3013570670,
    "email" : "kim@gmail.com"
}

###
DELETE http://localhost:4000/api/v1/employees/5fa871553762f41848cae61f HTTP/1.1